-- teamdb dump v1
-- Generado por teamdb-dump.sh. NO editar a mano; el diff se mergea por fila.
-- Source of truth: .opencode/context/team.db (la DB local). Este archivo es su fotografía.
INSERT INTO "concepts" ("id","slug","title","body_md","category","has_ui","updated_at") VALUES (1,'project-summary','Project Summary — Skalling v0.11.1','---
type: Concept
title: Project Summary — Skalling v0.11.1
description: Resumen estructural del proyecto skalling-dev-team (8 agentes, scripts bundle, team.db).
resource: README.md, AGENTS.md, VERSION
tags: [project-summary, skalling, opencode, agents, teamdb, conventions]
timestamp: 2026-09-13T13:14:52Z
agent: pau
confidence: 0.95
---

# Project Summary — Skalling v0.11.1

## What
Equipo de 8 agentes de IA para OpenCode: Alex (orquestador), Pol (spec), Jes (research), Sol (plan), Teo (engineer), Jhon (verifier), Luz (auditor), Pau (memory).

## Stack
Bash + Python 3, SQLite 3 con FTS5/WAL, OpenCode 1.18.29+. Sin package.json de aplicación — `package.json` solo trae opencode + plugins Node.

## Estructura
- `scripts/` — bundle canónico (con subdir `lib/`)
- `scripts/lib/` — helpers compartidos (lib-os.sh, lib-stack-detect.sh, lib-teamdb.sh, lib-memory-check.sh)
- `tests/` — suite de tests bash/python/js
- `docs/` — architecture.md, security-model.md
- `.opencode/` — bundle local (plano, sin subdir lib/) + context (team.db) + agents + skills + changes
- `sql/` — schemas + migrations
- `plugins/` — plugins OpenCode (skalling-goal.js, skalling-workflow.js, data-safety)
- `templates/`, `agents-base/`, `skills-base/`, `constitution/` — fuentes single-source
- `install-global.sh` — installer a `~/.config/opencode/`

## Versión
0.11.1 (de VERSION file). Compat: legacy_surface.work_in_progress=read_only_compatibility.

## Convenciones
- Slugs kebab-case (`auth-jwt`, `stack-postgres`)
- TeamDB es la fuente: `team.db` (no archivos .md son fuente)
- Markdown es export derivado (convention docs viven en DB)
- Escritura SQL parametrizada via `teamdb_exec.py` (R10)
- Audit log con `actor_source` (helper/trigger/application)
- Constitución single-source (install-global.sh la renderea a runtime)
- Cero secretos en DB; destructive operations requieren `teamdb_destructive` con backup','general',0,'2026-09-13 13:46:12');
INSERT INTO "proposals" ("id","slug","title","intent_md","questions_json","status","agent","decided_by","created_at","updated_at","decided_at") VALUES (1,'sqli-remediation-phase3','Fase 3 Remediacion SQLi Skalling','# Intent

Fase 3 Remediacion SQLi Skalling',NULL,'draft','pol',NULL,'2026-09-13T13:39:31Z','2026-09-13T13:39:31Z',NULL);
INSERT INTO "proposals" ("id","slug","title","intent_md","questions_json","status","agent","decided_by","created_at","updated_at","decided_at") VALUES (2,'scripts-parity-phase2','Paridad bundle-local .opencode/scripts/ vs fuente scripts/','# Intent

Paridad bundle-local .opencode/scripts/ vs fuente scripts/',NULL,'draft','pol',NULL,'2026-09-13T13:40:54Z','2026-09-13T13:40:54Z',NULL);
INSERT INTO "plans" ("id","slug","title","proposal_id","design_md","acceptance_md","status","agent","created_at","updated_at","completed_at","intent_md","version","created_by","updated_by") VALUES (1,'sqli-remediation-phase3','Fase 3 Remediacion SQLi Skalling',1,'Fase 3 del plan de remediacion SQLi. Auditoria estatica de 12 sitios sospechosos en scripts/*.sh contra los patrones pat_sqli y pat_sqli_dq de skalling-review.sh (líneas 447-491). Resultado: 0 sitios VULNERABLES en producción; 10 sitios clasificados como SEGURO-LITERAL o SEGURO-WHITELIST (sin variables del usuario en queries); 1 sitio ya usa _sql_quote (teamdb-attempt.sh:226, falso positivo del grep); 2 sitios usan escape manual con sed y se migran a teamdb_exec_value por consistencia y defensa en profundidad (wip-tree.sh:43, migrate-plans-md-to-db.sh:161). Estrategia de hardening: (1) centralizar lista de excepciones del linter con justificación inline en skalling-review.sh; (2) nuevo workflow .github/workflows/lint-sqli.yml que corre el linter sobre scripts/** excluyendo archivos exceptuados, falla si detecta pat_sqli o pat_sqli_dq, se dispara en push/PR a main y develop; (3) migrar los 2 sitios a teamdb_exec_value con bind params reales; (4) tests SQLi nuevos tests/teamdb-wip-tree-sqli.test.sh y tests/migrate-plans-sqli.test.sh que validan no-destrucción de tablas con payload SQLi; (5) integrar nuevos tests en teamdb-hardening-suite.sh; (6) documentar en MEMORY la decisión de mantener git-gate.py pre-push sin invocar skalling-review.sh (separación de scope: lint es CI, secretos/memDB/receipt son push).','Plan persistido con 9 tasks (1 raíz independiente, 1 fan-out, 3 paralelas, 1 fan-in, 1 paralelo adicional, 1 cierre) y 11 edges acíclicos. Cero sitios VULNERABLES en scripts/ post-migración. Lint CI activo en .github/workflows/lint-sqli.yml con lista de excepciones documentada (lib-teamdb.sh = provee helpers; skalling-review.sh = los busca; teamdb_exec.py = binding real; tests/** = fixtures). wip-tree.sh:43 y migrate-plans-md-to-db.sh:161 migrados a teamdb_exec_value con bind params Python (real parameter binding, no escape manual). Tests SQLi nuevos verdes (tests/teamdb-wip-tree-sqli.test.sh y tests/migrate-plans-sqli.test.sh) y agregados al listado de tests/teamdb-hardening-suite.sh. Decisión pre-push documentada en MEMORY (slugs y racional). Receipt final sellado por Pau con verificación de lint CI falla con caso sintético y árbol de tasks approved/resolved.

Referencia de alcance/aprobación: Pedido del usuario: req-20260913101348-44357, risk=medium, alcance explícito: auditoría sitios listados (teamdb-link.sh:54, teamdb-context-cache.sh:19, teamdb-export-md.sh:74, teamdb-skills-sync.sh:94, teamdb-migrate.sh:42, teamdb-restore.sh:105, skalling-metrics.sh:36/40, teamdb-attempt.sh:226 + wip-tree.sh:43 y migrate-plans-md-to-db.sh:161 que aparecieron durante la auditoría), plan DB-first con lista categorizada, spec linter CI bloqueante, plan migración por sitio, tests nuevos para gaps. Usuario explícitamente prohibió implementación y modificación de archivos del repo.','approved','sol','2026-09-13T13:39:31Z','2026-09-13 13:45:07',NULL,'# Intent

Fase 3 Remediacion SQLi Skalling',2,'sol','sol');
INSERT INTO "plans" ("id","slug","title","proposal_id","design_md","acceptance_md","status","agent","created_at","updated_at","completed_at","intent_md","version","created_by","updated_by") VALUES (2,'scripts-parity-phase2','Paridad bundle-local .opencode/scripts/ vs fuente scripts/',2,'Estrategia: paridad semántica con manifest explícito scripts/.bundle-manifest (formato TSV src<tab>dst) que define el mapping src→dst para el bundle local. scripts/build-local-snapshot.sh implementa tres modos: --apply (idempotente, copia atómica vía tmp+rename, preserva permisos con cp -p), --check (diff byte-a-byte con shasum, exit≠0 si drift), --dry-run (imprime plan de acción). El manifest incluye: scripts/skalling-*.sh→.opencode/scripts/skalling-*.sh (1:1), scripts/teamdb-*.sh→1:1, scripts/{dashboard-server,skalling-workflow,teamdb_exec,teamdb_guard,teamdb-destructive}.py→1:1, scripts/{mem-review,spec-memory-link,merge-helper,update,wip-tree,build-schema}.sh→1:1, scripts/lib/lib-{os,stack-detect,teamdb}.sh→.opencode/scripts/lib-{os,stack-detect,teamdb}.sh (aplanización lib/→plano intencional por compatibilidad con permisos de agentes y rutas usadas en runtime). Ignorados: __pycache__/, hooks/ (separado), lib-memory-check.sh (helper sourced, no ejecutable bundle), render-agent.sh y permission-policy.py (build tools), migrate-* (legacy), test-teamdb-*.sh (tests internos). tests/scripts-parity.test.sh ejecuta --check en sandbox y exige exit 0; verifica que cada archivo del manifest existe en destino con hash idéntico y que NO hay huérfanos en .opencode/scripts/ (whitelist de permitidos). setup-team-doctor.sh gana check_scripts_parity que invoca --check y emite warn/info según modo; con --strict promueve a error. .github/workflows/tests.yml agrega el test al step ''Run tests'' (gate en push a main/develop y PRs). Sincronización inicial: el primer --apply regenera .opencode/scripts/ cerrando el drift de Fase 1 (skalling-metrics.sh summary, teamdb-claim.sh in_review→approved, lib-teamdb.sh CHECK constraint DISCOVERY) en un commit que el gate debe validar.','(1) scripts/build-local-snapshot.sh existe con --apply/--check/--dry-run; (2) scripts/.bundle-manifest lista todos los bundle-esential con sha256 esperado; (3) bash scripts/build-local-snapshot.sh --check retorna 0 sin drift y exit≠0 con drift simulado (test cubre ambos casos); (4) tests/scripts-parity.test.sh pasa local y en CI; (5) bash setup-team-doctor.sh --strict falla con WARN de drift; (6) .github/workflows/tests.yml ejecuta el test en push a main/develop y PRs a main; (7) el commit de sincronización inicial cierra Fase 1 (lib-teamdb.sh CHECK DISCOVERY presente, skalling-metrics.sh summary presente, teamdb-claim.sh validaciones in_review→approved presentes en .opencode/scripts/); (8) tests/install-script-copies.test.sh sigue pasando (instalación global intacta); (9) AGENTS.md incluye sección ''Bundle local .opencode/scripts/'' con contrato, comandos de regeneración y referencia al gate de CI.

Referencia de alcance/aprobación: Plan técnico para Fase 2 del plan de remediación de Skalling. Riesgo medium. request_id req-20260913101348-44357 (clasificado FAST-TRACK pero requiere plan aprobado por la naturaleza medium). Decisión Opción B confirmada por el usuario: generación verificada sin symlinks; cp en install-global.sh se mantiene intacto; agregar tests/scripts-parity.test.sh con diff recursivo scripts/ vs .opencode/scripts/ en CI; check en setup-team-doctor.sh comparando hash de scripts instalados vs fuente del checkout; gate en CI falla si alguien toca scripts/x.sh y no actualiza .opencode/scripts/x.sh.','approved','sol','2026-09-13T13:40:54Z','2026-09-13 13:43:30',NULL,'# Intent

Paridad bundle-local .opencode/scripts/ vs fuente scripts/',2,'sol','sol');
INSERT INTO "tasks" ("id","plan_id","slug","title","description_md","acceptance_md","status","priority","owner","blocked_reason","resolution_md","order_index","estimated_minutes","due_date","created_at","updated_at","started_at","resolved_at","version","locked_by","locked_at","last_modified_by","purpose") VALUES (1,1,'task-auditar-sitios-sqli','Auditar sitios SQLi','','Plan persistido con task IDs, dependencias correctas y resultados verificables. Cero sitios VULNERABLES en scripts/ post-migracion. Lint CI activo en .github/workflows/lint-sqli.yml con archivo de excepciones documentado. Sitios wip-tree.sh y migrate-plans-md-to-db.sh migrados a teamdb_exec_value. Tests SQLi nuevos verdes y agregados a teamdb-hardening-suite.sh. Decision pre-push documentada en MEMORY.','pending',2,'sol',NULL,NULL,0,NULL,NULL,'2026-09-13T13:39:31Z','2026-09-13T13:39:31Z',NULL,NULL,1,NULL,NULL,NULL,'Fase 3 del plan de remediacion SQLi Skalling: auditoria estatica + lint CI bloqueante + migracion de 2 sitios a teamdb_exec_value + tests de cobertura. Riesgo medium.');
INSERT INTO "tasks" ("id","plan_id","slug","title","description_md","acceptance_md","status","priority","owner","blocked_reason","resolution_md","order_index","estimated_minutes","due_date","created_at","updated_at","started_at","resolved_at","version","locked_by","locked_at","last_modified_by","purpose") VALUES (2,1,'task-definir-excepciones-del-linter','Definir excepciones del linter','','Plan persistido con task IDs, dependencias correctas y resultados verificables. Cero sitios VULNERABLES en scripts/ post-migracion. Lint CI activo en .github/workflows/lint-sqli.yml con archivo de excepciones documentado. Sitios wip-tree.sh y migrate-plans-md-to-db.sh migrados a teamdb_exec_value. Tests SQLi nuevos verdes y agregados a teamdb-hardening-suite.sh. Decision pre-push documentada en MEMORY.','pending',2,'sol',NULL,NULL,1,NULL,NULL,'2026-09-13T13:39:31Z','2026-09-13T13:39:31Z',NULL,NULL,1,NULL,NULL,NULL,'Fase 3 del plan de remediacion SQLi Skalling: auditoria estatica + lint CI bloqueante + migracion de 2 sitios a teamdb_exec_value + tests de cobertura. Riesgo medium.');
INSERT INTO "tasks" ("id","plan_id","slug","title","description_md","acceptance_md","status","priority","owner","blocked_reason","resolution_md","order_index","estimated_minutes","due_date","created_at","updated_at","started_at","resolved_at","version","locked_by","locked_at","last_modified_by","purpose") VALUES (3,1,'task-activar-lint-sqli-en-ci','Activar lint SQLi en CI','','Plan persistido con task IDs, dependencias correctas y resultados verificables. Cero sitios VULNERABLES en scripts/ post-migracion. Lint CI activo en .github/workflows/lint-sqli.yml con archivo de excepciones documentado. Sitios wip-tree.sh y migrate-plans-md-to-db.sh migrados a teamdb_exec_value. Tests SQLi nuevos verdes y agregados a teamdb-hardening-suite.sh. Decision pre-push documentada en MEMORY.','pending',2,'sol',NULL,NULL,2,NULL,NULL,'2026-09-13T13:39:31Z','2026-09-13T13:39:31Z',NULL,NULL,1,NULL,NULL,NULL,'Fase 3 del plan de remediacion SQLi Skalling: auditoria estatica + lint CI bloqueante + migracion de 2 sitios a teamdb_exec_value + tests de cobertura. Riesgo medium.');
INSERT INTO "tasks" ("id","plan_id","slug","title","description_md","acceptance_md","status","priority","owner","blocked_reason","resolution_md","order_index","estimated_minutes","due_date","created_at","updated_at","started_at","resolved_at","version","locked_by","locked_at","last_modified_by","purpose") VALUES (4,1,'task-migrar-wip-tree-a-exec-value','Migrar wip-tree a exec_value','','Plan persistido con task IDs, dependencias correctas y resultados verificables. Cero sitios VULNERABLES en scripts/ post-migracion. Lint CI activo en .github/workflows/lint-sqli.yml con archivo de excepciones documentado. Sitios wip-tree.sh y migrate-plans-md-to-db.sh migrados a teamdb_exec_value. Tests SQLi nuevos verdes y agregados a teamdb-hardening-suite.sh. Decision pre-push documentada en MEMORY.','pending',2,'sol',NULL,NULL,3,NULL,NULL,'2026-09-13T13:39:31Z','2026-09-13T13:39:31Z',NULL,NULL,1,NULL,NULL,NULL,'Fase 3 del plan de remediacion SQLi Skalling: auditoria estatica + lint CI bloqueante + migracion de 2 sitios a teamdb_exec_value + tests de cobertura. Riesgo medium.');
INSERT INTO "tasks" ("id","plan_id","slug","title","description_md","acceptance_md","status","priority","owner","blocked_reason","resolution_md","order_index","estimated_minutes","due_date","created_at","updated_at","started_at","resolved_at","version","locked_by","locked_at","last_modified_by","purpose") VALUES (5,1,'task-migrar-migrate-plans-a-exec-value','Migrar migrate-plans a exec_value','','Plan persistido con task IDs, dependencias correctas y resultados verificables. Cero sitios VULNERABLES en scripts/ post-migracion. Lint CI activo en .github/workflows/lint-sqli.yml con archivo de excepciones documentado. Sitios wip-tree.sh y migrate-plans-md-to-db.sh migrados a teamdb_exec_value. Tests SQLi nuevos verdes y agregados a teamdb-hardening-suite.sh. Decision pre-push documentada en MEMORY.','pending',2,'sol',NULL,NULL,4,NULL,NULL,'2026-09-13T13:39:31Z','2026-09-13T13:39:31Z',NULL,NULL,1,NULL,NULL,NULL,'Fase 3 del plan de remediacion SQLi Skalling: auditoria estatica + lint CI bloqueante + migracion de 2 sitios a teamdb_exec_value + tests de cobertura. Riesgo medium.');
INSERT INTO "tasks" ("id","plan_id","slug","title","description_md","acceptance_md","status","priority","owner","blocked_reason","resolution_md","order_index","estimated_minutes","due_date","created_at","updated_at","started_at","resolved_at","version","locked_by","locked_at","last_modified_by","purpose") VALUES (6,1,'task-crear-tests-sqli-nuevos','Crear tests SQLi nuevos','','Plan persistido con task IDs, dependencias correctas y resultados verificables. Cero sitios VULNERABLES en scripts/ post-migracion. Lint CI activo en .github/workflows/lint-sqli.yml con archivo de excepciones documentado. Sitios wip-tree.sh y migrate-plans-md-to-db.sh migrados a teamdb_exec_value. Tests SQLi nuevos verdes y agregados a teamdb-hardening-suite.sh. Decision pre-push documentada en MEMORY.','pending',2,'sol',NULL,NULL,5,NULL,NULL,'2026-09-13T13:39:31Z','2026-09-13T13:39:31Z',NULL,NULL,1,NULL,NULL,NULL,'Fase 3 del plan de remediacion SQLi Skalling: auditoria estatica + lint CI bloqueante + migracion de 2 sitios a teamdb_exec_value + tests de cobertura. Riesgo medium.');
INSERT INTO "tasks" ("id","plan_id","slug","title","description_md","acceptance_md","status","priority","owner","blocked_reason","resolution_md","order_index","estimated_minutes","due_date","created_at","updated_at","started_at","resolved_at","version","locked_by","locked_at","last_modified_by","purpose") VALUES (7,1,'task-integrar-tests-al-hardening-suite','Integrar tests al hardening suite','','Plan persistido con task IDs, dependencias correctas y resultados verificables. Cero sitios VULNERABLES en scripts/ post-migracion. Lint CI activo en .github/workflows/lint-sqli.yml con archivo de excepciones documentado. Sitios wip-tree.sh y migrate-plans-md-to-db.sh migrados a teamdb_exec_value. Tests SQLi nuevos verdes y agregados a teamdb-hardening-suite.sh. Decision pre-push documentada en MEMORY.','pending',2,'sol',NULL,NULL,6,NULL,NULL,'2026-09-13T13:39:31Z','2026-09-13T13:39:31Z',NULL,NULL,1,NULL,NULL,NULL,'Fase 3 del plan de remediacion SQLi Skalling: auditoria estatica + lint CI bloqueante + migracion de 2 sitios a teamdb_exec_value + tests de cobertura. Riesgo medium.');
INSERT INTO "tasks" ("id","plan_id","slug","title","description_md","acceptance_md","status","priority","owner","blocked_reason","resolution_md","order_index","estimated_minutes","due_date","created_at","updated_at","started_at","resolved_at","version","locked_by","locked_at","last_modified_by","purpose") VALUES (8,1,'task-documentar-decision-pre-push','Documentar decision pre-push','','Plan persistido con task IDs, dependencias correctas y resultados verificables. Cero sitios VULNERABLES en scripts/ post-migracion. Lint CI activo en .github/workflows/lint-sqli.yml con archivo de excepciones documentado. Sitios wip-tree.sh y migrate-plans-md-to-db.sh migrados a teamdb_exec_value. Tests SQLi nuevos verdes y agregados a teamdb-hardening-suite.sh. Decision pre-push documentada en MEMORY.','pending',2,'sol',NULL,NULL,7,NULL,NULL,'2026-09-13T13:39:31Z','2026-09-13T13:39:31Z',NULL,NULL,1,NULL,NULL,NULL,'Fase 3 del plan de remediacion SQLi Skalling: auditoria estatica + lint CI bloqueante + migracion de 2 sitios a teamdb_exec_value + tests de cobertura. Riesgo medium.');
INSERT INTO "tasks" ("id","plan_id","slug","title","description_md","acceptance_md","status","priority","owner","blocked_reason","resolution_md","order_index","estimated_minutes","due_date","created_at","updated_at","started_at","resolved_at","version","locked_by","locked_at","last_modified_by","purpose") VALUES (9,1,'recibir-el-cierre-del-plan','Recibir el cierre del plan',NULL,'Receipt sellado en tabla receipts con tree_hash del diff acumulado, codigo de salida 0, y resumen de tareas verificadas (lint CI activo, sitios migrados, tests verdes).','pending',2,'sol',NULL,NULL,8,NULL,NULL,'2026-09-13T13:40:32Z','2026-09-13T13:40:32Z',NULL,NULL,1,NULL,NULL,NULL,'Generar receipt de cierre del plan Fase 3 con verificacion de que lint CI falla con caso de prueba y todas las tasks estan en estado approved o resolved.');
INSERT INTO "tasks" ("id","plan_id","slug","title","description_md","acceptance_md","status","priority","owner","blocked_reason","resolution_md","order_index","estimated_minutes","due_date","created_at","updated_at","started_at","resolved_at","version","locked_by","locked_at","last_modified_by","purpose") VALUES (10,2,'task-definir-spec-de-mapping-bundle-local-lista-expl-cita-src-dst-ignores-y-reglas-de-aplanizaci-n-lib-plano','Definir spec de mapping bundle-local: lista explícita src→dst, ignores y reglas de aplanización lib/→plano','','(1) build-local-snapshot.sh --apply deja .opencode/scripts/ idéntico byte-a-byte para todos los archivos del manifest; (2) tests/scripts-parity.test.sh pasa en CI con exit 0 cuando no hay drift y exit≠0 cuando sí lo hay; (3) setup-team-doctor.sh --strict sale 1 si hay drift; (4) .github/workflows/tests.yml ejecuta el test en push a main/develop y PRs; (5) el diff actual de Fase 1 (skalling-metrics.sh summary, teamdb-claim.sh in_review→approved, lib-teamdb.sh CHECK constraint DISCOVERY) queda resuelto por la sincronización inicial.','approved',2,'teo',NULL,'manifest+tooling generado por Teo en Fase 2 — scripts/.bundle-manifest (59 entries)',0,NULL,NULL,'2026-09-13T13:40:54Z','2026-09-13T13:49:34Z','1789307272','2026-09-13T13:49:34Z',1,NULL,NULL,NULL,'Asegurar que .opencode/scripts/ (bundle usado por agentes en SKALLING_ROOT) refleja el contenido bundle-esencial de scripts/ sin divergencia silenciosa, con generación verificada, test en CI y gate de PR.');
INSERT INTO "tasks" ("id","plan_id","slug","title","description_md","acceptance_md","status","priority","owner","blocked_reason","resolution_md","order_index","estimated_minutes","due_date","created_at","updated_at","started_at","resolved_at","version","locked_by","locked_at","last_modified_by","purpose") VALUES (11,2,'task-crear-scripts-build-local-snapshot-sh-aplica-el-manifest-soporta-check-exit-0-si-drift-dry-run-y-apply-idempotente','Crear scripts/build-local-snapshot.sh: aplica el manifest, soporta --check (exit≠0 si drift), --dry-run y --apply; idempotente','','(1) build-local-snapshot.sh --apply deja .opencode/scripts/ idéntico byte-a-byte para todos los archivos del manifest; (2) tests/scripts-parity.test.sh pasa en CI con exit 0 cuando no hay drift y exit≠0 cuando sí lo hay; (3) setup-team-doctor.sh --strict sale 1 si hay drift; (4) .github/workflows/tests.yml ejecuta el test en push a main/develop y PRs; (5) el diff actual de Fase 1 (skalling-metrics.sh summary, teamdb-claim.sh in_review→approved, lib-teamdb.sh CHECK constraint DISCOVERY) queda resuelto por la sincronización inicial.','approved',2,'teo',NULL,'—',1,NULL,NULL,'2026-09-13T13:40:54Z','2026-09-13T13:52:37Z','1789307378','2026-09-13T13:52:37Z',1,NULL,NULL,NULL,'Asegurar que .opencode/scripts/ (bundle usado por agentes en SKALLING_ROOT) refleja el contenido bundle-esencial de scripts/ sin divergencia silenciosa, con generación verificada, test en CI y gate de PR.');
INSERT INTO "tasks" ("id","plan_id","slug","title","description_md","acceptance_md","status","priority","owner","blocked_reason","resolution_md","order_index","estimated_minutes","due_date","created_at","updated_at","started_at","resolved_at","version","locked_by","locked_at","last_modified_by","purpose") VALUES (12,2,'task-sincronizaci-n-inicial-del-bundle-local-ejecutar-build-local-snapshot-sh-apply-regenerar-opencode-scripts-desde-scripts-commitear-el-delta-con-tests-scripts-parity-test-sh-pasando','Sincronización inicial del bundle local: ejecutar build-local-snapshot.sh --apply, regenerar .opencode/scripts/ desde scripts/, commitear el delta con tests/scripts-parity.test.sh pasando','','(1) build-local-snapshot.sh --apply deja .opencode/scripts/ idéntico byte-a-byte para todos los archivos del manifest; (2) tests/scripts-parity.test.sh pasa en CI con exit 0 cuando no hay drift y exit≠0 cuando sí lo hay; (3) setup-team-doctor.sh --strict sale 1 si hay drift; (4) .github/workflows/tests.yml ejecuta el test en push a main/develop y PRs; (5) el diff actual de Fase 1 (skalling-metrics.sh summary, teamdb-claim.sh in_review→approved, lib-teamdb.sh CHECK constraint DISCOVERY) queda resuelto por la sincronización inicial.','approved',2,'sol',NULL,'apply ejecutado: 59 archivos sincronizados, --check sale 0. drifts Fase 1 cerrados: skalling-metrics.sh summary, teamdb-claim.sh in_review->approved, lib-teamdb.sh DISCOVERY (verificado)',2,NULL,NULL,'2026-09-13T13:40:54Z','2026-09-13T13:51:09Z',NULL,'2026-09-13T13:51:09Z',1,NULL,NULL,NULL,'Asegurar que .opencode/scripts/ (bundle usado por agentes en SKALLING_ROOT) refleja el contenido bundle-esencial de scripts/ sin divergencia silenciosa, con generación verificada, test en CI y gate de PR.');
INSERT INTO "tasks" ("id","plan_id","slug","title","description_md","acceptance_md","status","priority","owner","blocked_reason","resolution_md","order_index","estimated_minutes","due_date","created_at","updated_at","started_at","resolved_at","version","locked_by","locked_at","last_modified_by","purpose") VALUES (13,2,'task-crear-tests-scripts-parity-test-sh-ejecuta-build-local-snapshot-sh-check-valida-hash-lista-hu-rfanos-ignora-pycache-y-archivos-no-listados-en-manifest','Crear tests/scripts-parity.test.sh: ejecuta build-local-snapshot.sh --check, valida hash, lista huérfanos, ignora __pycache__ y archivos no-listados-en-manifest','','(1) build-local-snapshot.sh --apply deja .opencode/scripts/ idéntico byte-a-byte para todos los archivos del manifest; (2) tests/scripts-parity.test.sh pasa en CI con exit 0 cuando no hay drift y exit≠0 cuando sí lo hay; (3) setup-team-doctor.sh --strict sale 1 si hay drift; (4) .github/workflows/tests.yml ejecuta el test en push a main/develop y PRs; (5) el diff actual de Fase 1 (skalling-metrics.sh summary, teamdb-claim.sh in_review→approved, lib-teamdb.sh CHECK constraint DISCOVERY) queda resuelto por la sincronización inicial.','approved',2,'sol',NULL,'tests/scripts-parity.test.sh creado: 8 casos (1 OK, 2 orphans, 3 drift positivo/negativo/falta, 4 idempotente, 5 dry-run no escribe, 6 shellcheck)',3,NULL,NULL,'2026-09-13T13:40:54Z','2026-09-13T13:52:37Z',NULL,'2026-09-13T13:52:37Z',1,NULL,NULL,NULL,'Asegurar que .opencode/scripts/ (bundle usado por agentes en SKALLING_ROOT) refleja el contenido bundle-esencial de scripts/ sin divergencia silenciosa, con generación verificada, test en CI y gate de PR.');
INSERT INTO "tasks" ("id","plan_id","slug","title","description_md","acceptance_md","status","priority","owner","blocked_reason","resolution_md","order_index","estimated_minutes","due_date","created_at","updated_at","started_at","resolved_at","version","locked_by","locked_at","last_modified_by","purpose") VALUES (14,2,'task-agregar-check-scripts-parity-al-setup-team-doctor-sh-usa-check-exit-0-con-strict-advertencia-clara-de-drift','Agregar check_scripts_parity al setup-team-doctor.sh: usa --check, exit≠0 con --strict, advertencia clara de drift','','(1) build-local-snapshot.sh --apply deja .opencode/scripts/ idéntico byte-a-byte para todos los archivos del manifest; (2) tests/scripts-parity.test.sh pasa en CI con exit 0 cuando no hay drift y exit≠0 cuando sí lo hay; (3) setup-team-doctor.sh --strict sale 1 si hay drift; (4) .github/workflows/tests.yml ejecuta el test en push a main/develop y PRs; (5) el diff actual de Fase 1 (skalling-metrics.sh summary, teamdb-claim.sh in_review→approved, lib-teamdb.sh CHECK constraint DISCOVERY) queda resuelto por la sincronización inicial.','approved',2,'teo',NULL,'check_scripts_parity() agregado: --check=0 → ok, drift → warn (err bajo --strict). Llamado desde main() tras check_teamdb. Verificado drift/warning/strict con edits y restore',4,NULL,NULL,'2026-09-13T13:40:54Z','2026-09-13T13:53:19Z','1789307560','2026-09-13T13:53:19Z',1,NULL,NULL,NULL,'Asegurar que .opencode/scripts/ (bundle usado por agentes en SKALLING_ROOT) refleja el contenido bundle-esencial de scripts/ sin divergencia silenciosa, con generación verificada, test en CI y gate de PR.');
INSERT INTO "tasks" ("id","plan_id","slug","title","description_md","acceptance_md","status","priority","owner","blocked_reason","resolution_md","order_index","estimated_minutes","due_date","created_at","updated_at","started_at","resolved_at","version","locked_by","locked_at","last_modified_by","purpose") VALUES (15,2,'task-integrar-tests-scripts-parity-test-sh-en-github-workflows-tests-yml-gate-en-push-a-main-develop-y-prs-a-main','Integrar tests/scripts-parity.test.sh en .github/workflows/tests.yml: gate en push a main/develop y PRs a main','','(1) build-local-snapshot.sh --apply deja .opencode/scripts/ idéntico byte-a-byte para todos los archivos del manifest; (2) tests/scripts-parity.test.sh pasa en CI con exit 0 cuando no hay drift y exit≠0 cuando sí lo hay; (3) setup-team-doctor.sh --strict sale 1 si hay drift; (4) .github/workflows/tests.yml ejecuta el test en push a main/develop y PRs; (5) el diff actual de Fase 1 (skalling-metrics.sh summary, teamdb-claim.sh in_review→approved, lib-teamdb.sh CHECK constraint DISCOVERY) queda resuelto por la sincronización inicial.','approved',2,'teo',NULL,'tests.yml: agregado bash tests/scripts-parity.test.sh al final del step "Run tests" (gate de push a main/develop y PRs a main). YAML validado.',5,NULL,NULL,'2026-09-13T13:40:54Z','2026-09-13T13:53:35Z','1789307602','2026-09-13T13:53:35Z',1,NULL,NULL,NULL,'Asegurar que .opencode/scripts/ (bundle usado por agentes en SKALLING_ROOT) refleja el contenido bundle-esencial de scripts/ sin divergencia silenciosa, con generación verificada, test en CI y gate de PR.');
INSERT INTO "tasks" ("id","plan_id","slug","title","description_md","acceptance_md","status","priority","owner","blocked_reason","resolution_md","order_index","estimated_minutes","due_date","created_at","updated_at","started_at","resolved_at","version","locked_by","locked_at","last_modified_by","purpose") VALUES (16,2,'documentar-contrato-del-bundle-local-opencode-scripts-en-agents-md-y-readme','Documentar contrato del bundle local .opencode/scripts/ en AGENTS.md y README',NULL,'Sección nueva en AGENTS.md titulada ''Bundle local .opencode/scripts/'' explica origen y contrato; README incluye bloque ''Regenerar bundle local'' con comando bash scripts/build-local-snapshot.sh --apply y --check; tests/scripts-parity.test.sh sigue pasando tras el cambio.','in_progress',2,'teo',NULL,NULL,6,NULL,NULL,'2026-09-13T13:42:57Z','1789307618','1789307618',NULL,1,NULL,NULL,NULL,'Visibilizar el contrato para futuros mantenedores: qué es .opencode/scripts/, por qué diverge estructuralmente de scripts/ (aplanización lib/), cómo regenerarlo, qué pasa si drift, y referencia al test de CI.');
INSERT INTO "task_dependencies" ("id","task_id","depends_on_task_id","type","created_at") VALUES (1,2,1,'blocks','2026-09-13T13:39:31Z');
INSERT INTO "task_dependencies" ("id","task_id","depends_on_task_id","type","created_at") VALUES (2,3,2,'blocks','2026-09-13T13:39:31Z');
INSERT INTO "task_dependencies" ("id","task_id","depends_on_task_id","type","created_at") VALUES (3,4,2,'blocks','2026-09-13T13:39:31Z');
INSERT INTO "task_dependencies" ("id","task_id","depends_on_task_id","type","created_at") VALUES (4,5,2,'blocks','2026-09-13T13:39:31Z');
INSERT INTO "task_dependencies" ("id","task_id","depends_on_task_id","type","created_at") VALUES (5,6,4,'blocks','2026-09-13T13:39:31Z');
INSERT INTO "task_dependencies" ("id","task_id","depends_on_task_id","type","created_at") VALUES (6,6,5,'blocks','2026-09-13T13:39:31Z');
INSERT INTO "task_dependencies" ("id","task_id","depends_on_task_id","type","created_at") VALUES (7,7,6,'blocks','2026-09-13T13:39:31Z');
INSERT INTO "task_dependencies" ("id","task_id","depends_on_task_id","type","created_at") VALUES (8,8,2,'blocks','2026-09-13T13:39:31Z');
INSERT INTO "task_dependencies" ("id","task_id","depends_on_task_id","type","created_at") VALUES (9,12,11,'blocks','2026-09-13T13:42:35Z');
INSERT INTO "task_dependencies" ("id","task_id","depends_on_task_id","type","created_at") VALUES (10,11,10,'blocks','2026-09-13T13:42:36Z');
INSERT INTO "task_dependencies" ("id","task_id","depends_on_task_id","type","created_at") VALUES (11,15,13,'blocks','2026-09-13T13:42:36Z');
INSERT INTO "task_dependencies" ("id","task_id","depends_on_task_id","type","created_at") VALUES (12,14,11,'blocks','2026-09-13T13:42:37Z');
INSERT INTO "task_dependencies" ("id","task_id","depends_on_task_id","type","created_at") VALUES (13,13,11,'blocks','2026-09-13T13:42:38Z');
INSERT INTO "task_dependencies" ("id","task_id","depends_on_task_id","type","created_at") VALUES (14,16,11,'blocks','2026-09-13T13:43:06Z');
INSERT INTO "task_dependencies" ("id","task_id","depends_on_task_id","type","created_at") VALUES (15,16,15,'blocks','2026-09-13T13:43:07Z');
INSERT INTO "task_dependencies" ("id","task_id","depends_on_task_id","type","created_at") VALUES (16,9,3,'blocks','2026-09-13T13:44:42Z');
INSERT INTO "task_dependencies" ("id","task_id","depends_on_task_id","type","created_at") VALUES (17,9,7,'blocks','2026-09-13T13:44:42Z');
INSERT INTO "task_dependencies" ("id","task_id","depends_on_task_id","type","created_at") VALUES (18,9,8,'blocks','2026-09-13T13:44:42Z');
INSERT INTO "task_claims" ("id","task_id","actor","attempt","input_hash","lease_until","status","claimed_at","released_at") VALUES (1,10,'teo',1,'6825521c60087ec741955029676a72932b44dce31473df87ea032cef1ef6b130',1789307572,'active','1789307272',NULL);
INSERT INTO "task_claims" ("id","task_id","actor","attempt","input_hash","lease_until","status","claimed_at","released_at") VALUES (2,11,'teo',1,'t11',1789307978,'active','1789307378',NULL);
INSERT INTO "task_claims" ("id","task_id","actor","attempt","input_hash","lease_until","status","claimed_at","released_at") VALUES (3,14,'teo',1,'t14',1789308160,'active','1789307560',NULL);
INSERT INTO "task_claims" ("id","task_id","actor","attempt","input_hash","lease_until","status","claimed_at","released_at") VALUES (4,15,'teo',1,'t15',1789308202,'active','1789307602',NULL);
INSERT INTO "task_claims" ("id","task_id","actor","attempt","input_hash","lease_until","status","claimed_at","released_at") VALUES (5,16,'teo',1,'t16',1789308218,'active','1789307618',NULL);
INSERT INTO "plan_history" ("id","plan_id","version","changed_by","changed_at","diff_md","snapshot_before","operation") VALUES (1,1,1,'sol','2026-09-13T13:39:31Z','Created with 8 tasks, 8 edges',NULL,'created');
INSERT INTO "plan_history" ("id","plan_id","version","changed_by","changed_at","diff_md","snapshot_before","operation") VALUES (2,1,2,'sol','2026-09-13T13:40:32Z','add task: recibir-el-cierre-del-plan (purpose: Generar receipt de cierre del plan Fase 3 con verificacion d)','[{"slug":"task-auditar-sitios-sqli","status":"pending","title":"Auditar sitios SQLi"},{"slug":"task-definir-excepciones-del-linter","status":"pending","title":"Definir excepciones del linter"},{"slug":"task-activar-lint-sqli-en-ci","status":"pending","title":"Activar lint SQLi en CI"},{"slug":"task-migrar-wip-tree-a-exec-value","status":"pending","title":"Migrar wip-tree a exec_value"},{"slug":"task-migrar-migrate-plans-a-exec-value","status":"pending","title":"Migrar migrate-plans a exec_value"},{"slug":"task-crear-tests-sqli-nuevos","status":"pending","title":"Crear tests SQLi nuevos"},{"slug":"task-integrar-tests-al-hardening-suite","status":"pending","title":"Integrar tests al hardening suite"},{"slug":"task-documentar-decision-pre-push","status":"pending","title":"Documentar decision pre-push"}]','amended');
INSERT INTO "plan_history" ("id","plan_id","version","changed_by","changed_at","diff_md","snapshot_before","operation") VALUES (3,2,1,'sol','2026-09-13T13:40:54Z','Created with 6 tasks, 5 edges',NULL,'created');
INSERT INTO "plan_history" ("id","plan_id","version","changed_by","changed_at","diff_md","snapshot_before","operation") VALUES (4,2,2,'sol','2026-09-13T13:42:57Z','add task: documentar-contrato-del-bundle-local-opencode-scripts-en-agents-md-y-readme (purpose: Visibilizar el contrato para futuros mantenedores: qué es .o)','[{"slug":"task-definir-spec-de-mapping-bundle-local-lista-expl-cita-src-dst-ignores-y-reglas-de-aplanizaci-n-lib-plano","status":"pending","title":"Definir spec de mapping bundle-local: lista explícita src→dst, ignores y reglas de aplanización lib/→plano"},{"slug":"task-crear-scripts-build-local-snapshot-sh-aplica-el-manifest-soporta-check-exit-0-si-drift-dry-run-y-apply-idempotente","status":"pending","title":"Crear scripts/build-local-snapshot.sh: aplica el manifest, soporta --check (exit≠0 si drift), --dry-run y --apply; idempotente"},{"slug":"task-sincronizaci-n-inicial-del-bundle-local-ejecutar-build-local-snapshot-sh-apply-regenerar-opencode-scripts-desde-scripts-commitear-el-delta-con-tests-scripts-parity-test-sh-pasando","status":"pending","title":"Sincronización inicial del bundle local: ejecutar build-local-snapshot.sh --apply, regenerar .opencode/scripts/ desde scripts/, commitear el delta con tests/scripts-parity.test.sh pasando"},{"slug":"task-crear-tests-scripts-parity-test-sh-ejecuta-build-local-snapshot-sh-check-valida-hash-lista-hu-rfanos-ignora-pycache-y-archivos-no-listados-en-manifest","status":"pending","title":"Crear tests/scripts-parity.test.sh: ejecuta build-local-snapshot.sh --check, valida hash, lista huérfanos, ignora __pycache__ y archivos no-listados-en-manifest"},{"slug":"task-agregar-check-scripts-parity-al-setup-team-doctor-sh-usa-check-exit-0-con-strict-advertencia-clara-de-drift","status":"pending","title":"Agregar check_scripts_parity al setup-team-doctor.sh: usa --check, exit≠0 con --strict, advertencia clara de drift"},{"slug":"task-integrar-tests-scripts-parity-test-sh-en-github-workflows-tests-yml-gate-en-push-a-main-develop-y-prs-a-main","status":"pending","title":"Integrar tests/scripts-parity.test.sh en .github/workflows/tests.yml: gate en push a main/develop y PRs a main"}]','amended');
INSERT INTO "routing_decisions" ("id","ts","user_intent","chosen_route","route_reason","agents_involved","outcome","completed_at") VALUES (1,'2026-09-13 13:45:54','Fase 2 implementación: build-local-snapshot.sh + .bundle-manifest + tests/scripts-parity.test.sh + check en setup-team-doctor.sh + CI gate; sincronización inicial que cierra los 3 drifts de Fase 1','DISCOVERY','clasificación automática','Alex → Jes → Pol','PENDING',NULL);
INSERT INTO "routing_decisions" ("id","ts","user_intent","chosen_route","route_reason","agents_involved","outcome","completed_at") VALUES (2,'2026-09-13 13:45:59','Fase 2 implementación: build-local-snapshot.sh + .bundle-manifest + tests/scripts-parity.test.sh + check en setup-team-doctor.sh + CI gate; sincronización inicial que cierra los 3 drifts de Fase 1','INLINE','clasificación automática','Alex → Sol → Teo → Jhon','PENDING',NULL);
INSERT INTO "routing_decisions" ("id","ts","user_intent","chosen_route","route_reason","agents_involved","outcome","completed_at") VALUES (3,'2026-09-13 13:46:14','Fase 2 implementación: build-local-snapshot.sh + .bundle-manifest + tests/scripts-parity.test.sh + check en setup-team-doctor.sh + CI gate; sincronización inicial cierra los 3 drifts de Fase 1','INLINE','clasificación automática','Alex → Sol → Teo → Jhon','PENDING',NULL);
INSERT INTO "routing_decisions" ("id","ts","user_intent","chosen_route","route_reason","agents_involved","outcome","completed_at") VALUES (4,'2026-09-13 13:46:17','Fase 3 implementación: lint CI gate bloqueante para SQLi; migrar wip-tree.sh:43 y migrate-plans-md-to-db.sh:161 a teamdb_exec_value; tests SQLi nuevos; integrar a hardening-suite','INLINE','clasificación automática','Alex → Sol → Teo → Jhon','PENDING',NULL);
